image: python:latest

stages:
  - test
  - deploy

test-all:
  stage: test
  script:
    - pip3 install requests
    - python3 -m unittest -v tests

deploy-pypi:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip3 install wheel
    - pip3 install twine
    - python3 setup.py sdist bdist_wheel
    - twine upload dist/*

